language: go

go:
 - 1.4.2
 - 1.5.3
 - 1.6

# Get deps, build, test, and ensure the code is gofmt'ed.
script:
 - go get -d -t -v ./...
 - go build -v ./...
 - go test -v ./...
 - diff <(gofmt -d .) <("")
